using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Irmandade.Data;
using System.Data.SQLite;
using Irmandade.Model;

namespace Irmandade
{
    public partial class ServicoForm : Form
    {
        BaseRepository baseRepo = new BaseRepository();
        string _CPF = null;

        public ServicoForm()
        {
            InitializeComponent();
        }

        public ServicoForm(string CPF)
        {
            InitializeComponent();
            _CPF = CPF;
        }

        private void ServicoForm_Load(object sender, EventArgs e)
        {
            CarregaDados();
            if (listBox.SelectedIndex == -1)
            {
                editButton.Enabled = false;
                // MessageBox.Show("Por favor selecione um item antes!");
            }
        }

        private void CarregaDados()
        {
            listBox.Items.Clear();

            DataTable dt = new DataTable();
            string sql;

            if (_CPF == null)
            {
                sql = "SELECT S.* FROM Servicos S";
            }
            else
            {
                // TODO load only the Servicos that the Pessoa doesn't have
                sql = "SELECT S.* FROM Servicos S " +
                            "WHERE (S.Id) NOT IN " +
                            "( SELECT S.Id " +
                            "FROM Servicos S INNER JOIN Pessoas_Servicos PS " +
                                "ON S.Id = PS.Servico_Id " +
                                "WHERE (PS.Pessoa_CPF == " + @" """ + _CPF + @""" " + "))";
            }
            try
            {
                dt = baseRepo.GetDataTableFromConnection<SQLiteConnection>(sql);

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    DataRow dr = dt.Rows[i];
                    listBox.Items.Add(dr[1]);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Erro:" + ex.Message);
            }
            finally
            {
                //if (conn.State == ConnectionState.Open)
                //{
                //    conn.Close();
                //}
            }
        }

        private void addButton_Click(object sender, EventArgs e)
        {
            if (listBox.SelectedIndex == -1)
            {
                MessageBox.Show("Erro: Selecione ou Crie algum Serviço!");
                return;                
            }                        

            // Concatenates the SQL Query suffix
            //var servicosList = new List<string>();

            //string sqlSuffix = "WHERE S.Descricao = " + @" """ + comboBox.SelectedItem.ToString() + @""" ";

            //string sql = @"SELECT * FROM Pessoas P
            //               INNER JOIN Pessoas_Servicos PS
            //                    ON (P.CPF = PS.Pessoa_CPF)
            //               INNER JOIN Servicos S
            //                    ON (PS.Servico_Id = S.Id)
            //                " + sqlSuffix;

            //testLabel.Text = sqlSuffix;

            //DataTable dt = baseRepo.GetDataTableFromConnection<SQLiteConnection>(sql);
            //dataGridView.DataSource = dt.DefaultView;


            using (SQLiteConnection conn = BaseRepository.DbConnection())
            {
                conn.Open();
                using (SQLiteCommand cmd = new SQLiteCommand(conn))
                {
                    cmd.CommandText = "INSERT INTO Pessoas_Servicos(Servicos_Id, Pessoa_CPF) " +
                                      "VALUES (@Servicos_Id, Pessoa_CPF)" + 
                                      "WHERE (Pessoa_CPF) in ";
                    cmd.Prepare();
                    cmd.Parameters.AddWithValue("@Servicos_Id", _CPF);
                    cmd.Parameters.AddWithValue("@Pessoa_CPF", listBox.SelectedItem.ToString());
                    try
                    {
                        cmd.ExecuteNonQuery();
                    }
                    catch (SQLiteException ex)
                    {
                        throw ex;
                    }
                    finally
                    {
                        conn.Close();
                    }
                }
            }

        }

        private int IncluirServico(string descricao)
        {
            int resultado = -1;
            
            using (SQLiteConnection conn = BaseRepository.DbConnection())
            {
                conn.Open();
                using (SQLiteCommand cmd = new SQLiteCommand(conn))
                {
                    cmd.CommandText = "INSERT INTO Servicos(Descricao) " +
                                       "VALUES (@Descricao)";
                    cmd.Prepare();
                    //Id autogenerated
                    cmd.Parameters.AddWithValue("@Descricao", descricao);                    
                    try
                    {
                        resultado = cmd.ExecuteNonQuery();
                    }                
                    catch (SQLiteException ex)
                    {
                        MessageBox.Show("Erro: Serviço não inserido!\n" + 
                                        "Detalhes do erro: \n"  + ex.Message);                        
                    }
                    finally
                    {
                        conn.Close();
                    }
                }
            }
            return resultado;
        }

        private void editButton_Click(object sender, EventArgs e)
        {
                        
        }

        private void listBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            // if any item is selectec in the list box, enable this button

            if (listBox.SelectedIndex == -1)
            {
                editButton.Enabled = false;                
            }
            else
            {                
                editButton.Enabled = true;
            }
                  
        }

        private void exitButton_Click(object sender, EventArgs e)
        {
            // TODO fazer alguma verificacao antes de fechar
            Close();
        }

        private void newButton_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(textBox.Text))
            {
                MessageBox.Show("Erro: Nome de Serviço inválido!");
                return;
            }
            IncluirServico(textBox.Text);
            textBox.Clear();
            CarregaDados();
        }
    }
}
