using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Irmandade.Data;
using System.Data.SQLite;
using Irmandade.Model;

namespace Irmandade
{
    public partial class ServicoForm : Form
    {
        BaseRepository baseRepo = new BaseRepository();

        public ServicoForm()
        {
            InitializeComponent();
        }

        private void ServicoForm_Load(object sender, EventArgs e)
        {
            CarregaDados();
            if (listBox.SelectedIndex == -1)
            {
                editButton.Enabled = false;
             //   MessageBox.Show("Please select an Item first!");
            }
        }

        private void CarregaDados()
        {
            listBox.Items.Clear();

            DataTable dt = new DataTable();            
            string sql = "SELECT S.* FROM Servicos S";            
            try
            {
                dt = baseRepo.GetDataTableFromConnection<SQLiteConnection>(sql);

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    DataRow dr = dt.Rows[i];
                    listBox.Items.Add(dr[1]);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Erro:" + ex.Message);
            }
            finally
            {
                //if (conn.State == ConnectionState.Open)
                //{
                //    conn.Close();
                //}
            }
        }

        private void addButton_Click(object sender, EventArgs e)
        {
            IncluirServico(textBox.Text);
            textBox.Clear();
            CarregaDados();            
        }

        private int IncluirServico(string descricao)
        {
            int resultado = -1;
            
            using (SQLiteConnection conn = BaseRepository.DbConnection())
            {
                conn.Open();
                using (SQLiteCommand cmd = new SQLiteCommand(conn))
                {
                    cmd.CommandText = "INSERT INTO Servicos(Descricao) " +
                                       "VALUES (@Descricao)";
                    cmd.Prepare();
                    //Id autogenerated
                    cmd.Parameters.AddWithValue("@Descricao", descricao);                    
                    try
                    {
                        resultado = cmd.ExecuteNonQuery();
                    }                
                    catch (SQLiteException ex)
                    {
                        MessageBox.Show("Erro: Serviço não inserido!\n" + 
                                        "Detalhes do erro: \n"  + ex.Message);                        
                    }
                    finally
                    {
                        conn.Close();
                    }
                }
            }
            return resultado;
        }

        private void editButton_Click(object sender, EventArgs e)
        {
                        
        }

        private void listBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            // if any item is selectec in the list box, enable this button

            if (listBox.SelectedIndex == -1)
            {
                editButton.Enabled = false;                
            }
            else
            {                
                editButton.Enabled = true;
            }
                  
        }

        private void exitButton_Click(object sender, EventArgs e)
        {
            // TODO fazer alguma verificacao antes de fechar
            Close();
        }
    }
}
